title: "Ilya Gorenburg | Frontend Developer. Behind the scenes"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
destination: "docs"
url: "https://ilya.gorenburg.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:year/:month/:day/:title

excerpt_separator: '[[MORE]]'

paginate: 10
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - octopress-autoprefixer
  - jekyll/tagging
  - jekyll-paginate

sass:
  style:      compressed

tag_page_layout: tag
tag_page_dir: tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
